# Generated by Django 4.2.7 on 2023-11-21 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=123, null=True)),
                ('first_name', models.CharField(max_length=123, null=True)),
                ('given_name', models.CharField(max_length=123, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=233, null=True)),
                ('phone', models.CharField(max_length=22, null=True)),
                ('eduction', models.CharField(max_length=123, null=True)),
                ('family_status', models.CharField(max_length=223, null=True)),
                ('children', models.CharField(max_length=123, null=True)),
                ('social_status', models.CharField(max_length=123, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterQuestionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_question', models.CharField(max_length=123, null=True)),
                ('variant_name', models.CharField(max_length=333, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_questions.registerquestion')),
            ],
        ),
    ]
