# Generated by Django 4.2.7 on 2023-11-22 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_order', models.CharField(choices=[('full', 'full'), ('month', 'month'), ('week', 'week')], max_length=123)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.UUIDField(unique=True, verbose_name=uuid.UUID('1a40fa47-8d65-43f8-b165-bf08ca8f67c0'))),
                ('order_status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
