# Generated by Django 4.2.7 on 2023-11-22 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('d1b68930-bf2c-44f2-9cd0-d18c7b854bcb'), editable=False, unique=True),
        ),
    ]
