# Generated by Django 4.2.7 on 2023-11-14 10:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('second_side_1', models.TextField()),
                ('second_side_2', models.TextField()),
                ('variant_1', models.CharField(max_length=333)),
                ('variant_2', models.CharField(max_length=333)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques_110.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSecondSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_side_1', models.TextField()),
                ('second_side_2', models.TextField()),
                ('second_side_3', models.TextField()),
                ('variant_1', models.CharField(max_length=333)),
                ('variant_2', models.CharField(max_length=333)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques_110.question')),
            ],
        ),
    ]
