# Generated by Django 4.2.7 on 2023-11-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_110', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='second_side_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='second_side_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant_2',
        ),
    ]
