# Generated by Django 4.2.7 on 2023-11-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_110', '0002_remove_question_second_side_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvariant',
            name='name',
            field=models.TextField(),
        ),
    ]
