# Generated by Django 4.2.7 on 2023-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_110', '0003_alter_questionvariant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsecondside',
            name='variant_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionsecondside',
            name='variant_2',
            field=models.TextField(),
        ),
    ]
