# Generated by Django 4.2.7 on 2023-11-15 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ques_110', '0004_alter_questionsecondside_variant_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPtichka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques_110.question')),
            ],
        ),
    ]
