# Generated by Django 4.2.7 on 2023-11-15 08:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_110', '0005_questionptichka'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='name_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='questionptichka',
            name='name_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionptichka',
            name='name_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='second_side_1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='second_side_1_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='second_side_2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='second_side_2_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='second_side_3_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='second_side_3_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='variant_1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='variant_1_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='variant_2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionsecondside',
            name='variant_2_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionvariant',
            name='name_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionvariant',
            name='name_uz',
            field=models.TextField(null=True),
        ),
    ]
