# Generated by Django 4.2.7 on 2023-11-15 10:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ques_110', '0006_question_name_ru_question_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='second_name',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='second_name_ru',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='second_name_uz',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.CreateModel(
            name='Question2variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_ru', ckeditor.fields.RichTextField(null=True)),
                ('name_uz', ckeditor.fields.RichTextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques_110.question')),
            ],
        ),
    ]
