# Generated by Django 4.2.7 on 2023-11-21 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ques_110', '0007_question_second_name_question_second_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question2variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_question_2', to='ques_110.question'),
        ),
        migrations.AlterField(
            model_name='questionptichka',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_done_front', to='ques_110.question'),
        ),
        migrations.AlterField(
            model_name='questionsecondside',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_side_question', to='ques_110.question'),
        ),
        migrations.AlterField(
            model_name='questionvariant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_variants', to='ques_110.question'),
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques_110.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
