# Generated by Django 4.2.7 on 2023-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
