# Generated by Django 4.2.7 on 2023-11-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
