# Generated by Django 4.2.7 on 2023-11-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
    ]
